[INFO   ] Logger: Record log in /storage/emulated/0/Python/Testes/.kivy/logs/kivy_22-02-28_38.txt
[INFO   ] Kivy: v2.0.0
[INFO   ] Kivy: Installed at "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/__init__.py"
[INFO   ] Python: v3.9.7 (default, Oct  9 2021, 08:02:40) 
[GCC 11.1.0]
[INFO   ] Python: Interpreter at "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/bin/python3"
[INFO   ] Factory: 186 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2 (img_pil, img_ffpyplayer ignored)
[INFO   ] Window: Provider: sdl2
[INFO   ] GL: Using the "OpenGL ES 2" graphics system
[INFO   ] GL: Backend used <sdl2>
[INFO   ] GL: OpenGL version <b'OpenGL ES 3.1 v1.r7p0-02rel0.4ea33e6671ff828e33c99c982634cd65'>
[INFO   ] GL: OpenGL vendor <b'ARM'>
[INFO   ] GL: OpenGL renderer <b'Mali-T720'>
[INFO   ] GL: OpenGL parsed version: 3, 1
[INFO   ] GL: Texture max size <8192>
[INFO   ] GL: Texture max units <16>
[INFO   ] Window: auto add sdl2 input provider
[INFO   ] Window: virtual keyboard not allowed, single mode, not docked
[INFO   ] GL: NPOT texture support is available
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "/storage/emulated/0/Python/Testes/__init__.py", line 24, in <module>
[WARNING] stderr:     Application().run()
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/app.py", line 949, in run
[WARNING] stderr:     self._run_prepare()
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/app.py", line 919, in _run_prepare
[WARNING] stderr:     root = self.build()
[WARNING] stderr:   File "/storage/emulated/0/Python/Testes/__init__.py", line 22, in build
[WARNING] stderr:     return Manager()
[WARNING] stderr:   File "/storage/emulated/0/Python/Testes/__init__.py", line 11, in __init__
[WARNING] stderr:     self.setup()
[WARNING] stderr:   File "/storage/emulated/0/Python/Testes/__init__.py", line 15, in setup
[WARNING] stderr:     self.add_widget(LoginView(name="Login"))
[WARNING] stderr:   File "/storage/emulated/0/Python/Testes/Views/Login.py", line 11, in __init__
[WARNING] stderr:     self.build()
[WARNING] stderr:   File "/storage/emulated/0/Python/Testes/Views/Login.py", line 14, in build
[WARNING] stderr:     view = Builder.load_file("Views/kv/Login.kv")
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/lang/builder.py", line 306, in load_file
[WARNING] stderr:     return self.load_string(data, **kwargs)
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/lang/builder.py", line 373, in load_string
[WARNING] stderr:     parser = Parser(content=string, filename=fn)
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/lang/parser.py", line 402, in __init__
[WARNING] stderr:     self.parse(content)
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/lang/parser.py", line 511, in parse
[WARNING] stderr:     objects, remaining_lines = self.parse_level(0, lines)
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/lang/parser.py", line 657, in parse_level
[WARNING] stderr:     _objects, _lines = self.parse_level(
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/lang/parser.py", line 566, in parse_level
[WARNING] stderr:     raise ParserException(self, ln,
[WARNING] stderr: kivy.lang.parser.ParserException: Parser: File "/storage/emulated/0/Python/Testes/Views/kv/Login.kv", line 5:
[WARNING] stderr: ...
[WARNING] stderr:       3:		canvas.before:
[WARNING] stderr:       4:				Color:
[WARNING] stderr: >>    5:					rgba: get_color_from_hex('#D3D4D5')
[WARNING] stderr:       6:			Rectangle:
[WARNING] stderr:       7:				pos: self.pos
[WARNING] stderr: ...
[WARNING] stderr: Invalid indentation, must be a multiple of 8 spaces
[WARNING] stderr: Exception in thread Thread-1:
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/threading.py", line 973, in _bootstrap_inner
[WARNING] stderr:     self.run()
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/threading.py", line 910, in run
[WARNING] stderr:     self._target(*self._args, **self._kwargs)
[WARNING] stderr:   File "/storage/emulated/0/Python/Testes/Views/Main.py", line 31, in connection_state
[WARNING] stderr:     self.manager.set_screen("Login")
[WARNING] stderr:   File "/storage/emulated/0/Python/Testes/__init__.py", line 18, in set_screen
[WARNING] stderr:     self.current = screen_name
[WARNING] stderr:   File "kivy/properties.pyx", line 498, in kivy.properties.Property.__set__
[WARNING] stderr:   File "kivy/properties.pyx", line 545, in kivy.properties.Property.set
[WARNING] stderr:   File "kivy/properties.pyx", line 600, in kivy.properties.Property.dispatch
[WARNING] stderr:   File "kivy/_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
[WARNING] stderr:   File "kivy/_event.pyx", line 1154, in kivy._event.EventObservers._dispatch
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/uix/screenmanager.py", line 1045, in on_current
[WARNING] stderr:     screen = self.get_screen(value)
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/lib/python3.9/site-packages/kivy/uix/screenmanager.py", line 1071, in get_screen
[WARNING] stderr:     raise ScreenManagerException('No Screen with name "%s".' % name)
[WARNING] stderr: kivy.uix.screenmanager.ScreenManagerException: No Screen with name "Login".
